export const colorTokens = {
	accent: {
		1: "var(--accent-1)",
		2: "var(--accent-2)",
		3: "var(--accent-3)",
		4: "var(--accent-4)",
		5: "var(--accent-5)",
		6: "var(--accent-6)",
		7: "var(--accent-7)",
		8: "var(--accent-8)",
		9: "var(--accent-9)",
		10: "var(--accent-10)",
		11: "var(--accent-11)",
		12: "var(--accent-12)",
	},
	accentAlpha: {
		1: "var(--accent-A1)",
		2: "var(--accent-A2)",
		3: "var(--accent-A3)",
		4: "var(--accent-A4)",
		5: "var(--accent-A5)",
		6: "var(--accent-A6)",
		7: "var(--accent-A7)",
		8: "var(--accent-A8)",
		9: "var(--accent-A9)",
		10: "var(--accent-A10)",
		11: "var(--accent-A11)",
		12: "var(--accent-A12)",
	},
	sand: {
		1: "var(--sand-1)",
		2: "var(--sand-2)",
		3: "var(--sand-3)",
		4: "var(--sand-4)",
		5: "var(--sand-5)",
		6: "var(--sand-6)",
		7: "var(--sand-7)",
		8: "var(--sand-8)",
		9: "var(--sand-9)",
		10: "var(--sand-10)",
		11: "var(--sand-11)",
		12: "var(--sand-12)",
	},
	sandAlpha: {
		1: "var(--sand-A1)",
		2: "var(--sand-A2)",
		3: "var(--sand-A3)",
		4: "var(--sand-A4)",
		5: "var(--sand-A5)",
		6: "var(--sand-A6)",
		7: "var(--sand-A7)",
		8: "var(--sand-A8)",
		9: "var(--sand-A9)",
		10: "var(--sand-A10)",
		11: "var(--sand-A11)",
		12: "var(--sand-A12)",
	},
} as const

export const colors = colorTokens
