export const colors = {
	accent: {
		1: "var(--accent-1)",
		2: "var(--accent-2)",
		3: "var(--accent-3)",
		4: "var(--accent-4)",
		5: "var(--accent-5)",
		6: "var(--accent-6)",
		7: "var(--accent-7)",
		8: "var(--accent-8)",
		9: "var(--accent-9)",
		10: "var(--accent-10)",
		11: "var(--accent-11)",
		12: "var(--accent-12)",
	},
	accentAlpha: {
		1: "var(--accent-A1)",
		2: "var(--accent-A2)",
		3: "var(--accent-A3)",
		4: "var(--accent-A4)",
		5: "var(--accent-A5)",
		6: "var(--accent-A6)",
		7: "var(--accent-A7)",
		8: "var(--accent-A8)",
		9: "var(--accent-A9)",
		10: "var(--accent-A10)",
		11: "var(--accent-A11)",
		12: "var(--accent-A12)",
	},
	gray: {
		1: "var(--gray-1)",
		2: "var(--gray-2)",
		3: "var(--gray-3)",
		4: "var(--gray-4)",
		5: "var(--gray-5)",
		6: "var(--gray-6)",
		7: "var(--gray-7)",
		8: "var(--gray-8)",
		9: "var(--gray-9)",
		10: "var(--gray-10)",
		11: "var(--gray-11)",
		12: "var(--gray-12)",
	},
	grayAlpha: {
		1: "var(--gray-A1)",
		2: "var(--gray-A2)",
		3: "var(--gray-A3)",
		4: "var(--gray-A4)",
		5: "var(--gray-A5)",
		6: "var(--gray-A6)",
		7: "var(--gray-A7)",
		8: "var(--gray-A8)",
		9: "var(--gray-A9)",
		10: "var(--gray-A10)",
		11: "var(--gray-A11)",
		12: "var(--gray-A12)",
	},
} as const
